[project]
name = 'Supply-Chain-Finance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.automated-payment]
path = 'contracts/automated-payment.clar'
clarity_version = 2
epoch = 2.5

[contracts.credit-scoring]
path = 'contracts/credit-scoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.invoice-token]
path = 'contracts/invoice-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
